# Generated by Django 3.2.18 on 2023-11-13 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fundingapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30, null=True)),
                ('lname', models.CharField(max_length=30, null=True)),
                ('email', models.CharField(max_length=30, unique=True)),
                ('phone', models.CharField(max_length=30, unique=True)),
                ('age', models.CharField(max_length=30, null=True)),
                ('country', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30, unique=True)),
                ('role', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30, null=True)),
                ('lname', models.CharField(max_length=30, null=True)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='images')),
                ('email', models.CharField(max_length=30, unique=True)),
                ('phone', models.CharField(max_length=30, unique=True)),
                ('age', models.CharField(max_length=30, null=True)),
                ('country', models.CharField(max_length=30, null=True)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fundingapp.log')),
            ],
        ),
        migrations.DeleteModel(
            name='login',
        ),
        migrations.AddField(
            model_name='investor',
            name='login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fundingapp.log'),
        ),
    ]
