# Generated by Django 4.2.3 on 2023-11-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fundingapp", "0002_auto_20231113_1348"),
    ]

    operations = [
        migrations.AlterField(
            model_name="startup",
            name="phone",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
