# Generated by Django 4.2.3 on 2023-11-16 05:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fundingapp", "0003_alter_startup_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investor",
            name="phone",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
