# Generated by Django 4.2.3 on 2023-11-17 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("fundingapp", "0004_alter_investor_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("projectname", models.CharField(max_length=30, null=True)),
                ("sector", models.CharField(max_length=30, null=True)),
                ("briefdesc", models.TextField(null=True)),
                ("about", models.TextField(null=True)),
                ("fountation", models.TextField(null=True)),
                ("amount", models.CharField(max_length=30, null=True)),
                ("share", models.CharField(max_length=30, null=True)),
                ("website", models.CharField(max_length=30, null=True)),
                ("location", models.CharField(max_length=30, null=True)),
                ("liscense", models.CharField(max_length=30, null=True)),
                (
                    "backimage",
                    models.ImageField(blank=True, null=True, upload_to="images"),
                ),
                (
                    "startupid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fundingapp.startup",
                    ),
                ),
            ],
        ),
    ]
