# Generated by Django 4.2.3 on 2023-11-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fundingapp", "0006_rename_fountation_project_foundation"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="initialamount",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
