# Generated by Django 4.2.3 on 2023-11-27 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("fundingapp", "0007_project_initialamount"),
    ]

    operations = [
        migrations.CreateModel(
            name="investment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("startupname", models.CharField(max_length=30, null=True)),
                ("investorname", models.CharField(max_length=30, null=True)),
                ("projectname", models.CharField(max_length=30, null=True)),
                ("share", models.CharField(max_length=30, null=True)),
                ("pricepershare", models.CharField(max_length=30, null=True)),
                ("investamount", models.CharField(max_length=30, null=True)),
                ("invest_date", models.CharField(max_length=100)),
                (
                    "investmentstatus",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "investorid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fundingapp.investor",
                    ),
                ),
                (
                    "projectid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fundingapp.project",
                    ),
                ),
                (
                    "startupid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fundingapp.startup",
                    ),
                ),
            ],
        ),
    ]
