# Generated by Django 4.2.3 on 2023-11-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fundingapp", "0008_investment"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="pricepershare",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
