# Generated by Django 4.2.3 on 2023-11-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fundingapp", "0009_project_pricepershare"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="projectstatus",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
