# Generated by Django 4.2.3 on 2023-11-29 05:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fundingapp", "0010_project_projectstatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="investment",
            name="period",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
